msgType:
  - COM
  - HC
localServerConfig:
  isUse: true
  name: server1
  port: 10001
  isCheckClient: false
  timeout: 30000
remoteServerConfig:
  isUse: false
  name: client1
  ip: 192.168.123.100
  port: 8083